### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by simonrglenn** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#2]
"...variable points to an object the represents Chrome's ..."
and object THAT represents

**Comment by sgharms** [comment]
Good spotting. @meg-gutshall 's PR fixed it.

(ProTip: @meg-gutshall if you type "Fixes #<NUM>" => it auto closes these when your PRs land. so smoove.)

**Comment by meg-gutshall** [comment]
Thank you @sgharms! I'll use that going forward.
