### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by gwhitlock8** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#4]
Change _the_ to _that_ in the sentence below.

The window variable points to an object ~the~ **that** represents Chrome's information about the browser, well, "window."

**Comment by kierblk** [comment]
As of 2/29/2020, the browser still shows this typo:
![Screen Shot 2020-02-29 at 7 02 15 PM](https://user-images.githubusercontent.com/49502059/75616960-2a03d300-5b26-11ea-9d37-0722177bec79.png)

However, the repo shows no error:
![Screen Shot 2020-02-29 at 7 01 35 PM](https://user-images.githubusercontent.com/49502059/75616968-443db100-5b26-11ea-96b2-3d868448ed57.png)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback. The materials have been updated.

Thanks for contributing! 💙
