### ISSUE TITLE
Unclear Wording / Possible Typo

### ISSUE THREAD

**Issue by ztw17** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#5]
As written: The window variable points to an object **the** represents Chrome's information about the browser, well, "window."

Is this supposed to be: "... to an object **that** represents Chrome's information..." ?

**Comment by kierblk** [comment]
Duplicate of #4

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback. We have updated the materials.

Thanks for contributing! 💙
