### ISSUE TITLE
Ordered list rendering incorrectly in browser

### ISSUE THREAD

**Issue by kierblk** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#6]
The ordered list outlining how DOM is created is rendering incorrectly in the browser.

**Expected behavior:**
A single ordered list, numbered 1-4 as the markdown intends. 

![Screen Shot 2020-02-29 at 6 43 17 PM](https://user-images.githubusercontent.com/49502059/75616801-f32cbd80-5b23-11ea-8fff-8385e5610242.png)

**Actual behavior:**
Two ordered lists, numbered 1-2 each. The image seems to split the ordered list.

![Screen Shot 2020-02-29 at 6 42 07 PM](https://user-images.githubusercontent.com/49502059/75616814-15264000-5b24-11ea-92fa-7ccc798f85df.png)

![Screen Shot 2020-02-29 at 6 49 14 PM](https://user-images.githubusercontent.com/49502059/75616822-36872c00-5b24-11ea-9e64-3d38e10a0786.png)

**Steps to Repeat:**
Visit [this lesson](https://learn.co/tracks/online-software-engineering-structured/front-end-web-programming/manipulating-the-dom/introduction-to-the-dom-to-get-started) via Firefox broswer. 

**Possible Steps to Correct:**
Unknown for sure. There appears to be different indentations for 1-2 than 3-4. Possible cause? 

![Screen Shot 2020-02-29 at 6 53 34 PM](https://user-images.githubusercontent.com/49502059/75616884-ec527a80-5b24-11ea-80ce-836e2225d5dc.png)

**Comment by Sdcrouse** [comment]
That's a weird bug. I'm guessing the Markdown might be conflicting with the Learn app itself. The ordered list appears to show up correctly on the README when you view it on Github.

**Comment by lizbur10** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide a link to the page that is rendering incorrectly, I'd be happy to take a second look!

As always, thanks for contributing! 💙
