### ISSUE TITLE
the DOM, a JavaScript object ...

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/fewpjs-introduction-to-the-dom-to-get-started#7]
Is it?
________________________________________________________________________________________________
Conclusion
In this lesson we met our partner, the DOM, a JavaScript object that is a representation of the HTML...

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
